// @generated by lenso-contract-codegen; do not edit.
use std::{fmt, rc::Rc};
use futures::future::LocalBoxFuture;
use lenso_kernel::{InvocationContext, NativeRequestEndpoint, NativeRequestFuture, NativeRequestHandle, PluginDependencies, RequestCapability, RuntimeFailure};

use lenso_plugin_authoring::{BoundCapabilityClient, CapabilityClient, CapabilityClientMany};
pub const CAPABILITY_ID: &str = "lenso.search@1";
pub const DESCRIPTOR_VERSION: &str = "1.0.0";
pub const PORTABLE: bool = true;
pub const CROSS_LANE_TRANSFER: bool = true;
pub const SEARCH_CAPABILITY_ID: &str = CAPABILITY_ID;
pub const SEARCH_DESCRIPTOR_VERSION: &str = DESCRIPTOR_VERSION;

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_provided_search { () => { "{\"capability_id\":\"lenso.search@1\",\"descriptor_version\":\"1.0.0\",\"operations\":[\"query_references\"],\"operation_kinds\":{},\"default_admission\":{\"queue_capacity\":0,\"max_concurrency\":1},\"operation_admissions\":{},\"event_admission\":null,\"cross_lane_transfer\":true}" }; }

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_required_search_client { () => { "{\"capability_id\":\"lenso.search@1\",\"descriptor_version\":\"1.0.0\",\"cardinality\":\"one\"}" }; }

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_required_many_search_client { () => { "{\"capability_id\":\"lenso.search@1\",\"descriptor_version\":\"1.0.0\",\"cardinality\":\"many\"}" }; }

pub const QUERY_REFERENCES_OPERATION: &str = "query_references";

pub use lenso_contract_runtime::{UnknownDomainError};
use lenso_contract_runtime::{decode_portable_json, encode_portable_json};

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct SearchRequest {
    #[serde(rename = "limit")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub limit: i64,
    #[serde(rename = "query")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub query: String,
    #[serde(rename = "scope_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub scope_id: String,
    #[serde(rename = "scope_kind")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub scope_kind: String,
    #[serde(rename = "source_kinds")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub source_kinds: Vec<String>,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct SearchResponse {
    #[serde(rename = "index_revision")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub index_revision: i64,
    #[serde(rename = "references")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub references: Vec<SearchResponseReferencesItem>,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct SearchResponseReferencesItem {
    #[serde(rename = "source_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub source_id: String,
    #[serde(rename = "source_kind")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub source_kind: String,
}

#[derive(Clone, Debug, PartialEq)]
pub enum QueryReferencesError {
    Forbidden,
    InvalidQuery,
    Unknown(UnknownDomainError),
}

#[derive(Debug)]
pub struct Search;
impl RequestCapability for Search {
    type Request = SearchRequest;
    type Response = SearchResponse;
    type DomainError = QueryReferencesError;
    const ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn invoke_native(endpoint: &dyn NativeRequestEndpoint, operation: &str, request: Self::Request, context: InvocationContext) -> NativeRequestFuture<Self> {
        if operation != QUERY_REFERENCES_OPERATION {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        }
        let Some(typed_endpoint) = endpoint
            .typed_endpoint()
            .and_then(|endpoint| endpoint.downcast_ref::<SearchRequestEndpoint>())
        else {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        };
        Rc::clone(&typed_endpoint.provider).query_references(context, request)
    }
}

impl serde::Serialize for QueryReferencesError {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        use serde::ser::SerializeMap;
        match self {
            Self::Forbidden => serializer.serialize_str("forbidden"),
            Self::InvalidQuery => serializer.serialize_str("invalid_query"),
            Self::Unknown(value) => {
                let mut map = serializer.serialize_map(Some(1 + usize::from(value.payload.is_some()) + value.extra.len()))?;
                map.serialize_entry("code", &value.code)?;
                if let Some(payload) = &value.payload {
                    map.serialize_entry("payload", payload)?;
                }
                for (key, extra) in &value.extra {
                    map.serialize_entry(key, extra)?;
                }
                map.end()
            },
        }
    }
}

impl<'de> serde::Deserialize<'de> for QueryReferencesError {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;
        match value {
            serde_json::Value::String(code) => match code.as_str() {
                "forbidden" => Ok(Self::Forbidden),
                "invalid_query" => Ok(Self::InvalidQuery),
                _ => Ok(Self::Unknown(UnknownDomainError { code, payload: None, extra: std::collections::BTreeMap::new() })),
            },
            serde_json::Value::Object(mut object) => {
                let Some(code) = object.remove("code").and_then(|value| value.as_str().map(ToOwned::to_owned)) else {
                    return Err(serde::de::Error::custom("Domain Error object is missing a string code"));
                };
                let payload = object.remove("payload");
                let extra = object.into_iter().collect::<std::collections::BTreeMap<_, _>>();
                Ok(Self::Unknown(UnknownDomainError { code, payload, extra }))
            }
            other => Err(serde::de::Error::custom(format!("Domain Error must be a string or object, got {other}"))),
        }
    }
}

pub fn encode_query_references_request(value: &SearchRequest) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_query_references_request(wire: &str) -> Result<SearchRequest, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_query_references_response(value: &SearchResponse) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_query_references_response(wire: &str) -> Result<SearchResponse, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_query_references_error(value: &QueryReferencesError) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_query_references_error(wire: &str) -> Result<QueryReferencesError, serde_json::Error> { decode_portable_json(wire) }

#[doc(hidden)]
pub trait __LensoIntoSearchQueryReferencesResult {
    fn __lenso_into_result(self) -> Result<Result<SearchResponse, QueryReferencesError>, RuntimeFailure>;
}
impl __LensoIntoSearchQueryReferencesResult for Result<SearchResponse, QueryReferencesError> {
    fn __lenso_into_result(self) -> Result<Result<SearchResponse, QueryReferencesError>, RuntimeFailure> { Ok(self) }
}
impl __LensoIntoSearchQueryReferencesResult for Result<Result<SearchResponse, QueryReferencesError>, RuntimeFailure> {
    fn __lenso_into_result(self) -> Result<Result<SearchResponse, QueryReferencesError>, RuntimeFailure> { self }
}
impl __LensoIntoSearchQueryReferencesResult for Result<SearchResponse, lenso_plugin_authoring::PluginError<QueryReferencesError, RuntimeFailure>> {
    fn __lenso_into_result(self) -> Result<Result<SearchResponse, QueryReferencesError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(lenso_plugin_authoring::PluginError::Domain(error)) => Ok(Err(error)),
            Err(lenso_plugin_authoring::PluginError::Runtime(error)) => Err(error),
        }
    }
}
impl __LensoIntoSearchQueryReferencesResult for Result<SearchResponse, SearchInvocationError> {
    fn __lenso_into_result(self) -> Result<Result<SearchResponse, QueryReferencesError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(SearchInvocationError::Domain(error)) => Ok(Err(error)),
            Err(SearchInvocationError::Runtime(error)) => Err(error),
        }
    }
}

pub trait SearchProvider: fmt::Debug + 'static {
    fn query_references(&self, context: InvocationContext, request: SearchRequest) -> NativeRequestFuture<Search>;
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_lower_search {
    ($plugin:ty, $support:path) => {
        use $support as __LensoNativeSupportSearch;
        impl $crate::SearchProvider for $plugin {
        fn query_references(&self, context: __LensoNativeSupportSearch::InvocationContext, request: $crate::SearchRequest) -> __LensoNativeSupportSearch::NativeRequestFuture<$crate::Search> {
            let plugin = self.clone();
            ::std::boxed::Box::pin(async move {
                let result = <$plugin>::query_references(&plugin, context, request).await;
                $crate::__LensoIntoSearchQueryReferencesResult::__lenso_into_result(result)
            })
        }
        }
    };
}

#[derive(Debug)]
struct SearchRequestEndpoint { provider: Rc<dyn SearchProvider> }

#[derive(Debug)]
pub struct SearchEndpoint<P: SearchProvider> { provider: Rc<P>, request_endpoint: SearchRequestEndpoint }
impl<P: SearchProvider> SearchEndpoint<P> {
    pub fn new(provider: P) -> Self {
        let provider = Rc::new(provider);
        let request_provider: Rc<dyn SearchProvider> = provider.clone();
        Self { provider, request_endpoint: SearchRequestEndpoint { provider: request_provider } }
    }
}

impl<P: SearchProvider> NativeRequestEndpoint for SearchEndpoint<P> {
    fn capability_id(&self) -> &'static str { CAPABILITY_ID }
    fn descriptor_version(&self) -> &'static str { DESCRIPTOR_VERSION }
    fn operations(&self) -> &'static [&'static str] { &[
        QUERY_REFERENCES_OPERATION,
    ] }
    fn typed_endpoint(&self) -> Option<&dyn std::any::Any> { Some(&self.request_endpoint) }
    fn invoke(&self, operation: &str, request: Box<dyn std::any::Any>, context: InvocationContext) -> LocalBoxFuture<'static, Result<Result<Box<dyn std::any::Any>, Box<dyn std::any::Any>>, RuntimeFailure>> {
        match operation {
            QUERY_REFERENCES_OPERATION => {
                let Ok(request) = request.downcast::<SearchRequest>() else {
                    return Box::pin(futures::future::ready(Err(RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID })));
                };
                let invocation = Rc::clone(&self.provider).query_references(context, *request);
                Box::pin(async move {
                    invocation.await.map(|result| {
                        result
                            .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                            .map_err(|error| Box::new(error) as Box<dyn std::any::Any>)
                    })
                })
            }
            _ => Box::pin(futures::future::ready(Err(RuntimeFailure::UnknownOperation { capability: CAPABILITY_ID, operation: operation.to_owned() }))),
        }
    }
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_endpoints_search {
    ($provider:expr, $support:path) => {{
        use $support as __LensoNativeSupport;
        let endpoint = ::std::rc::Rc::new($crate::SearchEndpoint::new($provider));
        (
            vec![endpoint.clone() as ::std::rc::Rc<dyn __LensoNativeSupport::NativeRequestEndpoint>],
            vec![],
            vec![],
        )
    }};
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_provide_search {
    ($provider:expr, $lifecycle:expr, $support:path) => {{
        use $support as __LensoNativeSupport;
        let (request_endpoints, stream_endpoints, event_endpoints) =
            $crate::__lenso_native_endpoints_search!($provider, $support);
        __LensoNativeSupport::NativePluginInstance::with_all_endpoints(
            request_endpoints,
            stream_endpoints,
            event_endpoints,
            $lifecycle,
        )
    }};
}

#[derive(Debug)]
pub struct SearchClient {
    query_references: NativeRequestHandle<Search>,
}
impl SearchClient {
    pub fn new(handle: NativeRequestHandle<Search>) -> Self {
        Self { query_references: handle }
    }

    pub fn from_dependencies(dependencies: &PluginDependencies) -> Result<Self, RuntimeFailure> {
        <Self as CapabilityClient>::from_dependencies(dependencies)
    }

    pub async fn query_references(&self, request: SearchRequest) -> Result<SearchResponse, SearchInvocationError> {
        self.query_references.invoke(QUERY_REFERENCES_OPERATION, request).await
            .map_err(SearchInvocationError::Runtime)?
            .map_err(SearchInvocationError::Domain)
    }

    pub async fn query_references_with_context(&self, context: InvocationContext, request: SearchRequest) -> Result<SearchResponse, SearchInvocationError> {
        self.query_references.invoke_with_context(QUERY_REFERENCES_OPERATION, context, request).await
            .map_err(SearchInvocationError::Runtime)?
            .map_err(SearchInvocationError::Domain)
    }
}

impl CapabilityClient for SearchClient {
    type Dependencies = PluginDependencies;
    type Error = RuntimeFailure;

    const CAPABILITY_ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn from_dependencies(dependencies: &PluginDependencies) -> Result<Self, RuntimeFailure> {
        Ok(Self {
            query_references: dependencies.one::<Search>()?,
        })
    }

    fn already_connected() -> RuntimeFailure {
        RuntimeFailure::PluginFailure {
            detail: format!("Capability Port {CAPABILITY_ID} was connected more than once"),
        }
    }
}

impl CapabilityClientMany for SearchClient {
    fn many_from_dependencies(
        dependencies: &PluginDependencies,
    ) -> Result<Vec<BoundCapabilityClient<Self>>, RuntimeFailure> {
        dependencies
            .bindings()
            .iter()
            .filter(|binding| binding.capability_id() == CAPABILITY_ID)
            .map(|binding| {
                Ok(BoundCapabilityClient::new(
                    binding.provider_instance(),
                    Self {
                    query_references: binding.handle().ok_or(RuntimeFailure::Unavailable { capability: CAPABILITY_ID })?.typed::<Search>()?,
                    },
                ))
            })
            .collect()
    }
}

#[derive(Clone, Debug, PartialEq)]
pub enum SearchInvocationError {
    Domain(QueryReferencesError),
    Runtime(RuntimeFailure),
}
