// @generated by lenso-contract-codegen; do not edit.
use std::{fmt, rc::Rc};
use futures::future::LocalBoxFuture;
use lenso_kernel::{InvocationContext, NativeRequestEndpoint, NativeRequestFuture, NativeRequestHandle, PluginDependencies, RequestCapability, RuntimeFailure};

use lenso_plugin_authoring::{BoundCapabilityClient, CapabilityClient, CapabilityClientMany};
pub const CAPABILITY_ID: &str = "lenso.search-index@1";
pub const DESCRIPTOR_VERSION: &str = "1.0.0";
pub const PORTABLE: bool = true;
pub const CROSS_LANE_TRANSFER: bool = true;
pub const SEARCH_INDEX_CAPABILITY_ID: &str = CAPABILITY_ID;
pub const SEARCH_INDEX_DESCRIPTOR_VERSION: &str = DESCRIPTOR_VERSION;

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_provided_search_index { () => { "{\"capability_id\":\"lenso.search-index@1\",\"descriptor_version\":\"1.0.0\",\"operations\":[\"delete_document\",\"upsert_document\"],\"operation_kinds\":{},\"default_admission\":{\"queue_capacity\":0,\"max_concurrency\":1},\"operation_admissions\":{},\"event_admission\":null,\"cross_lane_transfer\":true}" }; }

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_required_search_index_client { () => { "{\"capability_id\":\"lenso.search-index@1\",\"descriptor_version\":\"1.0.0\",\"cardinality\":\"one\"}" }; }

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_required_many_search_index_client { () => { "{\"capability_id\":\"lenso.search-index@1\",\"descriptor_version\":\"1.0.0\",\"cardinality\":\"many\"}" }; }

pub const DELETE_DOCUMENT_OPERATION: &str = "delete_document";
pub const UPSERT_DOCUMENT_OPERATION: &str = "upsert_document";

pub use lenso_contract_runtime::{UnknownDomainError};
use lenso_contract_runtime::{decode_portable_json, encode_portable_json};

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct DeleteDocumentRequest {
    #[serde(rename = "scope_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub scope_id: String,
    #[serde(rename = "scope_kind")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub scope_kind: String,
    #[serde(rename = "source_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub source_id: String,
    #[serde(rename = "source_kind")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub source_kind: String,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct DeleteDocumentResponse {
    #[serde(rename = "changed")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub changed: bool,
    #[serde(rename = "index_revision")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub index_revision: i64,
}

#[derive(Clone, Debug, PartialEq)]
pub enum DeleteDocumentError {
    Forbidden,
    InvalidDocument,
    Unknown(UnknownDomainError),
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct UpsertDocumentRequest {
    #[serde(rename = "scope_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub scope_id: String,
    #[serde(rename = "scope_kind")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub scope_kind: String,
    #[serde(rename = "search_text")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub search_text: String,
    #[serde(rename = "source_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub source_id: String,
    #[serde(rename = "source_kind")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub source_kind: String,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct UpsertDocumentResponse {
    #[serde(rename = "changed")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub changed: bool,
    #[serde(rename = "index_revision")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub index_revision: i64,
}

#[derive(Clone, Debug, PartialEq)]
pub enum UpsertDocumentError {
    Forbidden,
    InvalidDocument,
    Unknown(UnknownDomainError),
}

#[derive(Debug)]
pub struct SearchIndexDeleteDocument;
impl RequestCapability for SearchIndexDeleteDocument {
    type Request = DeleteDocumentRequest;
    type Response = DeleteDocumentResponse;
    type DomainError = DeleteDocumentError;
    const ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn invoke_native(endpoint: &dyn NativeRequestEndpoint, operation: &str, request: Self::Request, context: InvocationContext) -> NativeRequestFuture<Self> {
        if operation != DELETE_DOCUMENT_OPERATION {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        }
        let Some(typed_endpoint) = endpoint
            .typed_endpoint()
            .and_then(|endpoint| endpoint.downcast_ref::<SearchIndexRequestEndpoint>())
        else {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        };
        Rc::clone(&typed_endpoint.provider).delete_document(context, request)
    }
}

#[derive(Debug)]
pub struct SearchIndexUpsertDocument;
impl RequestCapability for SearchIndexUpsertDocument {
    type Request = UpsertDocumentRequest;
    type Response = UpsertDocumentResponse;
    type DomainError = UpsertDocumentError;
    const ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn invoke_native(endpoint: &dyn NativeRequestEndpoint, operation: &str, request: Self::Request, context: InvocationContext) -> NativeRequestFuture<Self> {
        if operation != UPSERT_DOCUMENT_OPERATION {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        }
        let Some(typed_endpoint) = endpoint
            .typed_endpoint()
            .and_then(|endpoint| endpoint.downcast_ref::<SearchIndexRequestEndpoint>())
        else {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        };
        Rc::clone(&typed_endpoint.provider).upsert_document(context, request)
    }
}

impl serde::Serialize for DeleteDocumentError {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        use serde::ser::SerializeMap;
        match self {
            Self::Forbidden => serializer.serialize_str("forbidden"),
            Self::InvalidDocument => serializer.serialize_str("invalid_document"),
            Self::Unknown(value) => {
                let mut map = serializer.serialize_map(Some(1 + usize::from(value.payload.is_some()) + value.extra.len()))?;
                map.serialize_entry("code", &value.code)?;
                if let Some(payload) = &value.payload {
                    map.serialize_entry("payload", payload)?;
                }
                for (key, extra) in &value.extra {
                    map.serialize_entry(key, extra)?;
                }
                map.end()
            },
        }
    }
}

impl<'de> serde::Deserialize<'de> for DeleteDocumentError {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;
        match value {
            serde_json::Value::String(code) => match code.as_str() {
                "forbidden" => Ok(Self::Forbidden),
                "invalid_document" => Ok(Self::InvalidDocument),
                _ => Ok(Self::Unknown(UnknownDomainError { code, payload: None, extra: std::collections::BTreeMap::new() })),
            },
            serde_json::Value::Object(mut object) => {
                let Some(code) = object.remove("code").and_then(|value| value.as_str().map(ToOwned::to_owned)) else {
                    return Err(serde::de::Error::custom("Domain Error object is missing a string code"));
                };
                let payload = object.remove("payload");
                let extra = object.into_iter().collect::<std::collections::BTreeMap<_, _>>();
                Ok(Self::Unknown(UnknownDomainError { code, payload, extra }))
            }
            other => Err(serde::de::Error::custom(format!("Domain Error must be a string or object, got {other}"))),
        }
    }
}

impl serde::Serialize for UpsertDocumentError {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        use serde::ser::SerializeMap;
        match self {
            Self::Forbidden => serializer.serialize_str("forbidden"),
            Self::InvalidDocument => serializer.serialize_str("invalid_document"),
            Self::Unknown(value) => {
                let mut map = serializer.serialize_map(Some(1 + usize::from(value.payload.is_some()) + value.extra.len()))?;
                map.serialize_entry("code", &value.code)?;
                if let Some(payload) = &value.payload {
                    map.serialize_entry("payload", payload)?;
                }
                for (key, extra) in &value.extra {
                    map.serialize_entry(key, extra)?;
                }
                map.end()
            },
        }
    }
}

impl<'de> serde::Deserialize<'de> for UpsertDocumentError {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;
        match value {
            serde_json::Value::String(code) => match code.as_str() {
                "forbidden" => Ok(Self::Forbidden),
                "invalid_document" => Ok(Self::InvalidDocument),
                _ => Ok(Self::Unknown(UnknownDomainError { code, payload: None, extra: std::collections::BTreeMap::new() })),
            },
            serde_json::Value::Object(mut object) => {
                let Some(code) = object.remove("code").and_then(|value| value.as_str().map(ToOwned::to_owned)) else {
                    return Err(serde::de::Error::custom("Domain Error object is missing a string code"));
                };
                let payload = object.remove("payload");
                let extra = object.into_iter().collect::<std::collections::BTreeMap<_, _>>();
                Ok(Self::Unknown(UnknownDomainError { code, payload, extra }))
            }
            other => Err(serde::de::Error::custom(format!("Domain Error must be a string or object, got {other}"))),
        }
    }
}

pub fn encode_delete_document_request(value: &DeleteDocumentRequest) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_delete_document_request(wire: &str) -> Result<DeleteDocumentRequest, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_delete_document_response(value: &DeleteDocumentResponse) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_delete_document_response(wire: &str) -> Result<DeleteDocumentResponse, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_delete_document_error(value: &DeleteDocumentError) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_delete_document_error(wire: &str) -> Result<DeleteDocumentError, serde_json::Error> { decode_portable_json(wire) }

pub fn encode_upsert_document_request(value: &UpsertDocumentRequest) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_upsert_document_request(wire: &str) -> Result<UpsertDocumentRequest, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_upsert_document_response(value: &UpsertDocumentResponse) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_upsert_document_response(wire: &str) -> Result<UpsertDocumentResponse, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_upsert_document_error(value: &UpsertDocumentError) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_upsert_document_error(wire: &str) -> Result<UpsertDocumentError, serde_json::Error> { decode_portable_json(wire) }

#[doc(hidden)]
pub trait __LensoIntoSearchIndexDeleteDocumentResult {
    fn __lenso_into_result(self) -> Result<Result<DeleteDocumentResponse, DeleteDocumentError>, RuntimeFailure>;
}
impl __LensoIntoSearchIndexDeleteDocumentResult for Result<DeleteDocumentResponse, DeleteDocumentError> {
    fn __lenso_into_result(self) -> Result<Result<DeleteDocumentResponse, DeleteDocumentError>, RuntimeFailure> { Ok(self) }
}
impl __LensoIntoSearchIndexDeleteDocumentResult for Result<Result<DeleteDocumentResponse, DeleteDocumentError>, RuntimeFailure> {
    fn __lenso_into_result(self) -> Result<Result<DeleteDocumentResponse, DeleteDocumentError>, RuntimeFailure> { self }
}
impl __LensoIntoSearchIndexDeleteDocumentResult for Result<DeleteDocumentResponse, lenso_plugin_authoring::PluginError<DeleteDocumentError, RuntimeFailure>> {
    fn __lenso_into_result(self) -> Result<Result<DeleteDocumentResponse, DeleteDocumentError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(lenso_plugin_authoring::PluginError::Domain(error)) => Ok(Err(error)),
            Err(lenso_plugin_authoring::PluginError::Runtime(error)) => Err(error),
        }
    }
}
impl __LensoIntoSearchIndexDeleteDocumentResult for Result<DeleteDocumentResponse, SearchIndexDeleteDocumentInvocationError> {
    fn __lenso_into_result(self) -> Result<Result<DeleteDocumentResponse, DeleteDocumentError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(SearchIndexDeleteDocumentInvocationError::Domain(error)) => Ok(Err(error)),
            Err(SearchIndexDeleteDocumentInvocationError::Runtime(error)) => Err(error),
        }
    }
}

#[doc(hidden)]
pub trait __LensoIntoSearchIndexUpsertDocumentResult {
    fn __lenso_into_result(self) -> Result<Result<UpsertDocumentResponse, UpsertDocumentError>, RuntimeFailure>;
}
impl __LensoIntoSearchIndexUpsertDocumentResult for Result<UpsertDocumentResponse, UpsertDocumentError> {
    fn __lenso_into_result(self) -> Result<Result<UpsertDocumentResponse, UpsertDocumentError>, RuntimeFailure> { Ok(self) }
}
impl __LensoIntoSearchIndexUpsertDocumentResult for Result<Result<UpsertDocumentResponse, UpsertDocumentError>, RuntimeFailure> {
    fn __lenso_into_result(self) -> Result<Result<UpsertDocumentResponse, UpsertDocumentError>, RuntimeFailure> { self }
}
impl __LensoIntoSearchIndexUpsertDocumentResult for Result<UpsertDocumentResponse, lenso_plugin_authoring::PluginError<UpsertDocumentError, RuntimeFailure>> {
    fn __lenso_into_result(self) -> Result<Result<UpsertDocumentResponse, UpsertDocumentError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(lenso_plugin_authoring::PluginError::Domain(error)) => Ok(Err(error)),
            Err(lenso_plugin_authoring::PluginError::Runtime(error)) => Err(error),
        }
    }
}
impl __LensoIntoSearchIndexUpsertDocumentResult for Result<UpsertDocumentResponse, SearchIndexUpsertDocumentInvocationError> {
    fn __lenso_into_result(self) -> Result<Result<UpsertDocumentResponse, UpsertDocumentError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(SearchIndexUpsertDocumentInvocationError::Domain(error)) => Ok(Err(error)),
            Err(SearchIndexUpsertDocumentInvocationError::Runtime(error)) => Err(error),
        }
    }
}

pub trait SearchIndexProvider: fmt::Debug + 'static {
    fn delete_document(&self, context: InvocationContext, request: DeleteDocumentRequest) -> NativeRequestFuture<SearchIndexDeleteDocument>;
    fn upsert_document(&self, context: InvocationContext, request: UpsertDocumentRequest) -> NativeRequestFuture<SearchIndexUpsertDocument>;
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_lower_search_index {
    ($plugin:ty, $support:path) => {
        use $support as __LensoNativeSupportSearchIndex;
        impl $crate::SearchIndexProvider for $plugin {
        fn delete_document(&self, context: __LensoNativeSupportSearchIndex::InvocationContext, request: $crate::DeleteDocumentRequest) -> __LensoNativeSupportSearchIndex::NativeRequestFuture<$crate::SearchIndexDeleteDocument> {
            let plugin = self.clone();
            ::std::boxed::Box::pin(async move {
                let result = <$plugin>::delete_document(&plugin, context, request).await;
                $crate::__LensoIntoSearchIndexDeleteDocumentResult::__lenso_into_result(result)
            })
        }
        fn upsert_document(&self, context: __LensoNativeSupportSearchIndex::InvocationContext, request: $crate::UpsertDocumentRequest) -> __LensoNativeSupportSearchIndex::NativeRequestFuture<$crate::SearchIndexUpsertDocument> {
            let plugin = self.clone();
            ::std::boxed::Box::pin(async move {
                let result = <$plugin>::upsert_document(&plugin, context, request).await;
                $crate::__LensoIntoSearchIndexUpsertDocumentResult::__lenso_into_result(result)
            })
        }
        }
    };
}

#[derive(Debug)]
struct SearchIndexRequestEndpoint { provider: Rc<dyn SearchIndexProvider> }

#[derive(Debug)]
pub struct SearchIndexEndpoint<P: SearchIndexProvider> { provider: Rc<P>, request_endpoint: SearchIndexRequestEndpoint }
impl<P: SearchIndexProvider> SearchIndexEndpoint<P> {
    pub fn new(provider: P) -> Self {
        let provider = Rc::new(provider);
        let request_provider: Rc<dyn SearchIndexProvider> = provider.clone();
        Self { provider, request_endpoint: SearchIndexRequestEndpoint { provider: request_provider } }
    }
}

impl<P: SearchIndexProvider> NativeRequestEndpoint for SearchIndexEndpoint<P> {
    fn capability_id(&self) -> &'static str { CAPABILITY_ID }
    fn descriptor_version(&self) -> &'static str { DESCRIPTOR_VERSION }
    fn operations(&self) -> &'static [&'static str] { &[
        DELETE_DOCUMENT_OPERATION,
        UPSERT_DOCUMENT_OPERATION,
    ] }
    fn typed_endpoint(&self) -> Option<&dyn std::any::Any> { Some(&self.request_endpoint) }
    fn invoke(&self, operation: &str, request: Box<dyn std::any::Any>, context: InvocationContext) -> LocalBoxFuture<'static, Result<Result<Box<dyn std::any::Any>, Box<dyn std::any::Any>>, RuntimeFailure>> {
        match operation {
            DELETE_DOCUMENT_OPERATION => {
                let Ok(request) = request.downcast::<DeleteDocumentRequest>() else {
                    return Box::pin(futures::future::ready(Err(RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID })));
                };
                let invocation = Rc::clone(&self.provider).delete_document(context, *request);
                Box::pin(async move {
                    invocation.await.map(|result| {
                        result
                            .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                            .map_err(|error| Box::new(error) as Box<dyn std::any::Any>)
                    })
                })
            },
            UPSERT_DOCUMENT_OPERATION => {
                let Ok(request) = request.downcast::<UpsertDocumentRequest>() else {
                    return Box::pin(futures::future::ready(Err(RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID })));
                };
                let invocation = Rc::clone(&self.provider).upsert_document(context, *request);
                Box::pin(async move {
                    invocation.await.map(|result| {
                        result
                            .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                            .map_err(|error| Box::new(error) as Box<dyn std::any::Any>)
                    })
                })
            }
            _ => Box::pin(futures::future::ready(Err(RuntimeFailure::UnknownOperation { capability: CAPABILITY_ID, operation: operation.to_owned() }))),
        }
    }
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_endpoints_search_index {
    ($provider:expr, $support:path) => {{
        use $support as __LensoNativeSupport;
        let endpoint = ::std::rc::Rc::new($crate::SearchIndexEndpoint::new($provider));
        (
            vec![endpoint.clone() as ::std::rc::Rc<dyn __LensoNativeSupport::NativeRequestEndpoint>],
            vec![],
            vec![],
        )
    }};
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_provide_search_index {
    ($provider:expr, $lifecycle:expr, $support:path) => {{
        use $support as __LensoNativeSupport;
        let (request_endpoints, stream_endpoints, event_endpoints) =
            $crate::__lenso_native_endpoints_search_index!($provider, $support);
        __LensoNativeSupport::NativePluginInstance::with_all_endpoints(
            request_endpoints,
            stream_endpoints,
            event_endpoints,
            $lifecycle,
        )
    }};
}

#[derive(Debug)]
pub struct SearchIndexClient {
    delete_document: NativeRequestHandle<SearchIndexDeleteDocument>,
    upsert_document: NativeRequestHandle<SearchIndexUpsertDocument>,
}
impl SearchIndexClient {
    pub fn from_dependencies(dependencies: &PluginDependencies) -> Result<Self, RuntimeFailure> {
        <Self as CapabilityClient>::from_dependencies(dependencies)
    }

    pub async fn delete_document(&self, request: DeleteDocumentRequest) -> Result<DeleteDocumentResponse, SearchIndexDeleteDocumentInvocationError> {
        self.delete_document.invoke(DELETE_DOCUMENT_OPERATION, request).await
            .map_err(SearchIndexDeleteDocumentInvocationError::Runtime)?
            .map_err(SearchIndexDeleteDocumentInvocationError::Domain)
    }

    pub async fn delete_document_with_context(&self, context: InvocationContext, request: DeleteDocumentRequest) -> Result<DeleteDocumentResponse, SearchIndexDeleteDocumentInvocationError> {
        self.delete_document.invoke_with_context(DELETE_DOCUMENT_OPERATION, context, request).await
            .map_err(SearchIndexDeleteDocumentInvocationError::Runtime)?
            .map_err(SearchIndexDeleteDocumentInvocationError::Domain)
    }

    pub async fn upsert_document(&self, request: UpsertDocumentRequest) -> Result<UpsertDocumentResponse, SearchIndexUpsertDocumentInvocationError> {
        self.upsert_document.invoke(UPSERT_DOCUMENT_OPERATION, request).await
            .map_err(SearchIndexUpsertDocumentInvocationError::Runtime)?
            .map_err(SearchIndexUpsertDocumentInvocationError::Domain)
    }

    pub async fn upsert_document_with_context(&self, context: InvocationContext, request: UpsertDocumentRequest) -> Result<UpsertDocumentResponse, SearchIndexUpsertDocumentInvocationError> {
        self.upsert_document.invoke_with_context(UPSERT_DOCUMENT_OPERATION, context, request).await
            .map_err(SearchIndexUpsertDocumentInvocationError::Runtime)?
            .map_err(SearchIndexUpsertDocumentInvocationError::Domain)
    }
}

impl CapabilityClient for SearchIndexClient {
    type Dependencies = PluginDependencies;
    type Error = RuntimeFailure;

    const CAPABILITY_ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn from_dependencies(dependencies: &PluginDependencies) -> Result<Self, RuntimeFailure> {
        Ok(Self {
            delete_document: dependencies.one::<SearchIndexDeleteDocument>()?,
            upsert_document: dependencies.one::<SearchIndexUpsertDocument>()?,
        })
    }

    fn already_connected() -> RuntimeFailure {
        RuntimeFailure::PluginFailure {
            detail: format!("Capability Port {CAPABILITY_ID} was connected more than once"),
        }
    }
}

impl CapabilityClientMany for SearchIndexClient {
    fn many_from_dependencies(
        dependencies: &PluginDependencies,
    ) -> Result<Vec<BoundCapabilityClient<Self>>, RuntimeFailure> {
        dependencies
            .bindings()
            .iter()
            .filter(|binding| binding.capability_id() == CAPABILITY_ID)
            .map(|binding| {
                Ok(BoundCapabilityClient::new(
                    binding.provider_instance(),
                    Self {
                    delete_document: binding.handle().ok_or(RuntimeFailure::Unavailable { capability: CAPABILITY_ID })?.typed::<SearchIndexDeleteDocument>()?,
                    upsert_document: binding.handle().ok_or(RuntimeFailure::Unavailable { capability: CAPABILITY_ID })?.typed::<SearchIndexUpsertDocument>()?,
                    },
                ))
            })
            .collect()
    }
}

#[derive(Clone, Debug, PartialEq)]
pub enum SearchIndexDeleteDocumentInvocationError {
    Domain(DeleteDocumentError),
    Runtime(RuntimeFailure),
}
#[derive(Clone, Debug, PartialEq)]
pub enum SearchIndexUpsertDocumentInvocationError {
    Domain(UpsertDocumentError),
    Runtime(RuntimeFailure),
}
